@startuml Password Generator

abstract class Engine {
    +{abstract} generatePassword(): string
    #defaultSourceString: string
}

class EngineFactory {
    +createEngine(EngineType): Engine
}

Password *-- Engine
Engine <|-- StandardEngine
Engine <|-- AlphaNumEngine
AlphaNumEngine <|-- PronounceableEngine
Application *- Password
EngineType --* Password
EngineTYpe --* Application
ApplicationTest --> Application
PasswordTest --> Password
StandardEngineTest --> StandardEngine
AlphaNumEngineTest --> AlphaNumEngine
PronounceableEngineTest --> PronounceableEngine
CommandLineParserTest --> CommandLineParser
PasswordSettingsTest --> PasswordSettings
PasswordGeneratorTest --> PasswordGenerator
DisplayTest --> Display

class StandardEngine {
    +generatePassword(): string
    -buildAsciiSequence(): string
}

class AlphaNumEngine {
    +generatePassword(): string
}

class PronounceableEngine {
    +generatePassword(): string
    -generateLettersSequence(): string
    -computeNumberOfPasses(): int
}

class Password {
    -passwordLength: int
    -password: string
    +setPasswordEngine(selectedEngineName: EngineType): void
    +setPasswordLength(length: int): void
    +generatePasswordWithEngine(): void
    +getPassword(): string
}

enum EngineType {
        Standard,
        Alphanumerique,
        Prononçable
}

set namespaceSeparator ::
annotation RandomUtils::RandomUtils {
    initializeRandomEngine(): void
    getRandomNumber(): int
    getRandomCharSequence(): string
    getRandomCharFromString(): string
    getRandomSpecials(): string
    getRandomConsonants(): string
    getRandomVowels(): string
    getRandomDigits(): string
}

annotation StringUtils::StringUtils {
    getUpperString(): string
    buildLowerUpperCharSequence(): string
    buildAsciiCharSequence(): string
}

class Application {
    +getPasswordsList(): vector
    #passwordsList: vector
}

class Display {
    +displayPasswordList(): void
}

class CommandLineParser {
    +readCommandLineArguments(): bool
    +selectPasswordEngineFromOptArgs(): void
    #getPwdLengthFromOptArgs(): void
    #getNumberPasswordsFromOptArgs(): void
}

class PasswordSettings {
    +setNumberOfPasswords(): void
    +getNumberOfPasswords(): int
    +setPasswordLength(): void
    +getPasswordLength(): int
    -passwordLength: int
    -numberOfPasswords: int
}

class PasswordGenerator {
    +getPasswordEngine(): EngineName
    +initializeGenerator(): void
    +runGenerator(): void
}

CommandLineParser --* Application
PasswordSettings --* Application
PasswordGenerator --* Application
Display --* Application

class ApplicationTest
class PasswordTest
class StandardEngineTest
class AlphaNumEngineTest
class PronounceableEngineTest
class CommandLineParserTest
class PasswordSettingsTest
class PasswordGeneratorTest
class DisplayTest

@enduml